### ISSUE TITLE
verisure/vacation/active only published to MQTT when active

### ISSUE THREAD

**Issue by TheLion** [xibriz/verisure-mqtt#3]
verisure/vacation/active is only published to MQTT when True. If it is False, nothing is published.

**Comment by xibriz** [comment]
Are you sure? When I tested I got:

> verisure/vacation/cid 1234567
> verisure/vacation/turnOffPetImmunity False
> verisure/vacation/fromDate 2019-05-01T14:00:00.000Z
> verisure/vacation/toDate 2019-05-31T10:00:00.000Z
> verisure/vacation/temporaryContactName (null)
> verisure/vacation/active False

If I "deleted" the vacation information, none of the topics are published.

**Comment by TheLion** [comment]
Ah... That explains it. I deleted it. But when there are no vacations present, shouldn't False (or anything) be published to MQTT? Else there is no trigger what-so-ever that anything changed and nothing can get the altered state from MQTT.

**Comment by xibriz** [comment]
I tough about it, but left it alone since I don't use this functionality. 

I think it will be fine because when you add vacation information, `active` will be `False` before the `fromDate` starts, then change to `True` (I'm guessing), then change back to `False` when we pass `toDate`. 

Then you will probably delete this information from Verisure and nothing happens. 

I agree with you, I can change the behavior so that the topic `verisure/vacation/active` publish `False` if no vacation data is available.

**Comment by xibriz** [comment]
Unless you delete the information when in an `active = True` state off course :) 

I will fix it.

**Comment by xibriz** [comment]
Fixed in commit #8522e21
